#!/bin/bash
# Claude Code Wrapper Script with pseudo-TTY and file-based output

export HOME=/root
export PATH="/usr/local/bin:$PATH"
export USER=root
export TERM=xterm-256color

# Disable Claude Code's internal cron so sessions launched through this
# wrapper rely on external cron instead.
export CLAUDE_CODE_DISABLE_CRON=1

# Auto-compact each persistent Claude Code session as its context approaches 150K tokens
##export CLAUDE_CODE_AUTO_COMPACT_WINDOW="${CLAUDE_CODE_AUTO_COMPACT_WINDOW:-150000}"
export CLAUDE_CODE_AUTO_COMPACT_WINDOW="${CLAUDE_CODE_AUTO_COMPACT_WINDOW:-200000}"
export CLAUDE_AUTOCOMPACT_PCT_OVERRIDE="${CLAUDE_AUTOCOMPACT_PCT_OVERRIDE:-50}"
# Hide Claude Code's bundled dev-workflow skills (code-review, verify, init, ...)
# so the skills catalog only lists Ninja's own .claude/skills/.
export CLAUDE_CODE_DISABLE_BUNDLED_SKILLS=1

# Auto-compact each persistent Claude Code session as its context approaches
# ~150K tokens, so the monitor's and orchestrator's named sessions (-n/-r
# monitor|orchestrator) don't grow unbounded across cycles. NOTE: this knob is
# undocumented/best-effort — Claude Code officially exposes only auto-compact
# on/off, not a token threshold — so treat it as a hint. Overridable via env.
##export CLAUDE_CODE_AUTO_COMPACT_WINDOW="${CLAUDE_CODE_AUTO_COMPACT_WINDOW:-150000}"

# Use the repo-local settings.json (generated by the orchestrator).
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SETTINGS_FILE="$SCRIPT_DIR/settings.json"

# Create a temp file for output
TMPFILE=$(mktemp)
trap "rm -f $TMPFILE" EXIT

# Locate the claude binary (npm global install location varies by environment)
CLAUDE_BIN=""
for candidate in "/root/.local/bin/claude" "/usr/local/bin/claude" "/usr/bin/claude" "$(which claude 2>/dev/null)"; do
    if [ -x "$candidate" ]; then
        CLAUDE_BIN="$candidate"
        break
    fi
done

if [ -z "$CLAUDE_BIN" ]; then
    echo "ERROR: claude binary not found. Tried: /root/.local/bin/claude, /usr/local/bin/claude, /usr/bin/claude" >&2
    exit 1
fi

# Run claude — prompt is fed via stdin from CLAUDE_PROMPT_FILE to avoid
# E2BIG / MAX_ARG_STRLEN when the prompt exceeds the ~128 KB kernel limit.
# script(1) cannot forward piped stdin, so we run the binary directly.
"$CLAUDE_BIN" --settings "$SETTINGS_FILE" "$@" < "$CLAUDE_PROMPT_FILE" > "$TMPFILE" 2>&1

# Clean and output the result (remove ANSI codes, OSC sequences, and control chars)
cat "$TMPFILE" | tr -d '\r' | sed 's/\x1b\[[0-9;]*[a-zA-Z]//g; s/\x1b\[[?][0-9]*[a-zA-Z]//g; s/\x1b\[<u//g; s/\x1b\][0-9]*;[^\x07]*\x07//g'
